<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[4]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[5]=array(3,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[6]=array(3,1,1,'5YWs5Y+45Y6G56iL');
$cfg_Cs[7]=array(0,1,1,'5bm754Gv54mH');
$cfg_Cs[8]=array(3,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[9]=array(2,1,1,'5pe25bCa5aSW5aWX');
$cfg_Cs[10]=array(2,1,1,'6IGM5Lia5aWX6KOF');
$cfg_Cs[11]=array(0,1,1,'5oub5ZWG5Yqg55uf');
$cfg_Cs[12]=array(11,1,1,'5Yqg55uf5LyY5Yq/');
$cfg_Cs[13]=array(11,1,1,'5Yqg55uf5rWB56iL');
$cfg_Cs[14]=array(11,1,1,'5Yqg55uf5p2h5Lu2');
?>