<?php
$z[0]=Array("type","\r\n        <p>[field:typename/]</p>\r\n        ",363,441);
$z[0][4]['typeid']="3";
$z[1]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",452,551);
$z[1][4]['typeid']="3";
$z[1][4]['row']="3";
$z[2]=Array("type","\r\n        <p>[field:typename/]</p>\r\n        ",594,672);
$z[2][4]['typeid']="2";
$z[3]=Array("arclist"," <a href=\"[field:arcurl/]\">[field:title/]</a> ",683,780);
$z[3][4]['typeid']="2";
$z[3][4]['row']="3";
$z[4]=Array("type","\r\n        <p>[field:typename/]</p>\r\n        ",823,901);
$z[4][4]['typeid']="1";
$z[5]=Array("arclist"," <a href=\"[field:arcurl/]\">[field:title/]</a> ",912,1009);
$z[5][4]['typeid']="1";
$z[5][4]['row']="3";
$z[6]=Array("type","\r\n        <p>[field:typename/]</p>\r\n        ",1052,1131);
$z[6][4]['typeid']="11";
$z[7]=Array("channel"," <a href=\"[field:typelink/]\">[field:typename/]</a> ",1142,1242);
$z[7][4]['typeid']="11";
$z[7][4]['row']="3";
$z[8]=Array("global","",1329,1352);
$z[8][4]['name']="cfg_kefu";
$z[9]=Array("global","",1818,1844);
$z[9][4]['name']="cfg_powerby";
$z[10]=Array("global","",1857,1881);
$z[10][4]['name']="cfg_beian";
$z[11]=Array("flink","  [field:link /]  ",1954,2031);
$z[11][4]['titlelen']="30";
$z[11][4]['row']="3";
$z[11][4]['type']="text";
$z[12]=Array("global","",2283,2306);
$z[12][4]['name']="cfg_kefu";
$z[13]=Array("global","",2481,2503);
$z[13][4]['name']="cfg_tel";

?>