<?php
$z[0]=Array("field","",379,398);
$z[0][4]['name']="title";
$z[1]=Array("global","",399,425);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",469,528);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",563,592);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1997,2032);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","\r\n          <p>[field:typename/]</p>\r\n          ",2249,2331);
$z[5][4]['typeid']="2";
$z[6]=Array("channel"," <a href=\"[field:typelink/]\" [field:rel/]>[field:typename/]</a> ",2372,2559);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a class='on' href='~typelink~' ~rel~><span>~typename~</span></a>";
$z[7]=Array("include","",2588,2635);
$z[7][4]['filename']="left_nav_contact.htm";
$z[8]=Array("type","\r\n        <p>[field:typename/]</p>\r\n        ",2706,2784);
$z[8][4]['typeid']="9";
$z[9]=Array("list","\r\n        <div class=\"gallery_box\"> <img src=\"[field:picname/]\"> <span>[field:title/]</span> <a href=\"[field:arcurl/]\"></a> </div>\r\n        ",2870,3047);
$z[9][4]['pagesize']="6";
$z[10]=Array("pagelist","",3110,3166);
$z[10][4]['listitem']="pre,next,pageno";
$z[10][4]['listsize']="1";
$z[11]=Array("include","",3274,3311);
$z[11][4]['filename']="footer.htm";

?>