<?php
$z[0]=Array("field","",379,398);
$z[0][4]['name']="title";
$z[1]=Array("global","",399,425);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",469,528);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",563,592);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1971,2006);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","\r\n          <p>[field:typename/]</p>\r\n          ",2236,2318);
$z[5][4]['typeid']="4";
$z[6]=Array("global","",2381,2408);
$z[6][4]['name']="cfg_describe";
$z[7]=Array("global","",2439,2462);
$z[7][4]['name']="cfg_kefu";
$z[8]=Array("global","",2493,2517);
$z[8][4]['name']="cfg_email";
$z[9]=Array("global","",2548,2574);
$z[9][4]['name']="cfg_address";
$z[10]=Array("global","",2605,2632);
$z[10][4]['name']="cfg_postcode";
$z[11]=Array("include","",4092,4129);
$z[11][4]['filename']="footer.htm";

?>