<?php
$z[0]=Array("field","",379,398);
$z[0][4]['name']="title";
$z[1]=Array("global","",399,425);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",469,528);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",563,592);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1971,2006);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","\r\n          <p>[field:typename/]</p>\r\n          ",2224,2306);
$z[5][4]['typeid']="3";
$z[6]=Array("channel"," <a href=\"[field:typelink/]\" [field:rel/]>[field:typename/]</a> ",2347,2534);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<a class='on' href='~typelink~' ~rel~><span>~typename~</span></a>";
$z[7]=Array("include","",2563,2610);
$z[7][4]['filename']="left_nav_contact.htm";
$z[8]=Array("field","",2672,2733);
$z[8][4]['name']="typename";
$z[8][4]['function']="”GetTypeName(@me)”";
$z[9]=Array("field","",2773,2794);
$z[9][4]['name']="content";
$z[10]=Array("include","",2889,2926);
$z[10][4]['filename']="footer.htm";

?>